/* Auto-generated by scripts/import-gallery.js — do not edit by hand */
export type GalleryCategory =
  | "all"
  | "maternity"
  | "newborn"
  | "milestone"
  | "family"
  | "traditional"
  | "christmas"
  | "portrait";

export type GalleryItem = {
  id: string;
  src: string;
  alt: string;
  caption: string;
  category: Exclude<GalleryCategory, "all">;
  width: number;
  height: number;
  ratio: number;
};

export const galleryCategories: { id: GalleryCategory; label: string }[] = [
  {
    "id": "all",
    "label": "All"
  },
  {
    "id": "maternity",
    "label": "Maternity"
  },
  {
    "id": "newborn",
    "label": "Newborn"
  },
  {
    "id": "milestone",
    "label": "Milestone"
  },
  {
    "id": "family",
    "label": "Family"
  },
  {
    "id": "traditional",
    "label": "Traditional"
  },
  {
    "id": "christmas",
    "label": "Christmas"
  },
  {
    "id": "portrait",
    "label": "Portrait"
  }
];

export const galleryItems: GalleryItem[] = [
  {
    "id": "06945e86f30c",
    "src": "/images/gallery/christmas-img_9091-06945e.jpg",
    "alt": "christmas photography by Javies Photography Studio",
    "caption": "Christmas",
    "category": "christmas",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "b55358ec5f6f",
    "src": "/images/gallery/christmas-img_9615-b55358.jpg",
    "alt": "christmas photography by Javies Photography Studio",
    "caption": "Christmas",
    "category": "christmas",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "0e6a3e20cf2f",
    "src": "/images/gallery/christmas-img_9727-0e6a3e.jpg",
    "alt": "christmas photography by Javies Photography Studio",
    "caption": "Christmas",
    "category": "christmas",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "4523376abfb4",
    "src": "/images/gallery/christmas-img_9759-452337.jpg",
    "alt": "christmas photography by Javies Photography Studio",
    "caption": "Christmas",
    "category": "christmas",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "9431a51acb05",
    "src": "/images/gallery/christmas-javi7996-9431a5.jpg",
    "alt": "christmas photography by Javies Photography Studio",
    "caption": "Christmas",
    "category": "christmas",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "8d5a9bc5c915",
    "src": "/images/gallery/christmas-joey@1-(15)-8d5a9b.jpg",
    "alt": "christmas photography by Javies Photography Studio",
    "caption": "Christmas",
    "category": "christmas",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "836344d57456",
    "src": "/images/gallery/christmas-jpsi0521-836344.jpg",
    "alt": "christmas photography by Javies Photography Studio",
    "caption": "Christmas",
    "category": "christmas",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "8bdd6060d653",
    "src": "/images/gallery/christmas-jpsi0595-8bdd60.jpg",
    "alt": "christmas photography by Javies Photography Studio",
    "caption": "Christmas",
    "category": "christmas",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "f332480a7904",
    "src": "/images/gallery/christmas-jpsi0719-f33248.jpg",
    "alt": "christmas photography by Javies Photography Studio",
    "caption": "Christmas",
    "category": "christmas",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "3e355b4de2bc",
    "src": "/images/gallery/christmas-jpsi7087-3e355b.jpg",
    "alt": "christmas photography by Javies Photography Studio",
    "caption": "Christmas",
    "category": "christmas",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "e4b40c240e57",
    "src": "/images/gallery/christmas-jpsi7441-e4b40c.jpg",
    "alt": "christmas photography by Javies Photography Studio",
    "caption": "Christmas",
    "category": "christmas",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "37a67eff9001",
    "src": "/images/gallery/christmas-jpsi7742-37a67e.jpg",
    "alt": "christmas photography by Javies Photography Studio",
    "caption": "Christmas",
    "category": "christmas",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "f1a56fdd5623",
    "src": "/images/gallery/christmas-jpsi7825-f1a56f.jpg",
    "alt": "christmas photography by Javies Photography Studio",
    "caption": "Christmas",
    "category": "christmas",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "49866c314b97",
    "src": "/images/gallery/christmas-jpsi9929-49866c.jpg",
    "alt": "christmas photography by Javies Photography Studio",
    "caption": "Christmas",
    "category": "christmas",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "20da43d6495c",
    "src": "/images/gallery/family-244a6531-20da43.jpg",
    "alt": "family photography by Javies Photography Studio",
    "caption": "Family",
    "category": "family",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "60ac6a781595",
    "src": "/images/gallery/family-ankomaa@1-(41)-60ac6a.jpg",
    "alt": "family photography by Javies Photography Studio",
    "caption": "Family",
    "category": "family",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "fa342e356e2d",
    "src": "/images/gallery/family-ankomaa@1-(41)-fa342e.jpg",
    "alt": "family photography by Javies Photography Studio",
    "caption": "Family",
    "category": "family",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "4f1bb8d8d197",
    "src": "/images/gallery/family-javi0534-4f1bb8.jpg",
    "alt": "family photography by Javies Photography Studio",
    "caption": "Family",
    "category": "family",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "e169c5291eaf",
    "src": "/images/gallery/family-sreyhan@3ms-(13)-e169c5.jpg",
    "alt": "family photography by Javies Photography Studio",
    "caption": "Family",
    "category": "family",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "1a07b347d6ed",
    "src": "/images/gallery/family-sreyhan@3ms-(8)-1a07b3.jpg",
    "alt": "family photography by Javies Photography Studio",
    "caption": "Family",
    "category": "family",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "3dba2a2f9023",
    "src": "/images/gallery/maternity-_c7a0049-3dba2a.jpg",
    "alt": "maternity photography by Javies Photography Studio",
    "caption": "Maternity",
    "category": "maternity",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "314d66b498d4",
    "src": "/images/gallery/maternity-_c7a0102-314d66.jpg",
    "alt": "maternity photography by Javies Photography Studio",
    "caption": "Maternity",
    "category": "maternity",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "6cf46a43b685",
    "src": "/images/gallery/maternity-_u0a3415b-6cf46a.jpg",
    "alt": "maternity photography by Javies Photography Studio",
    "caption": "Maternity",
    "category": "maternity",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "a4e22e874891",
    "src": "/images/gallery/maternity-_u0a3446b-a4e22e.jpg",
    "alt": "maternity photography by Javies Photography Studio",
    "caption": "Maternity",
    "category": "maternity",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "36e6a0a035e7",
    "src": "/images/gallery/maternity-3c7a9985-36e6a0.jpg",
    "alt": "maternity photography by Javies Photography Studio",
    "caption": "Maternity",
    "category": "maternity",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "3840ddf9bdf8",
    "src": "/images/gallery/maternity-6-3840dd.jpg",
    "alt": "maternity photography by Javies Photography Studio",
    "caption": "Maternity",
    "category": "maternity",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "41d744198ccb",
    "src": "/images/gallery/maternity-javi0298-41d744.jpg",
    "alt": "maternity photography by Javies Photography Studio",
    "caption": "Maternity",
    "category": "maternity",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "74bbe2c0c1fb",
    "src": "/images/gallery/maternity-javi0380-74bbe2.jpg",
    "alt": "maternity photography by Javies Photography Studio",
    "caption": "Maternity",
    "category": "maternity",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "138c7b251936",
    "src": "/images/gallery/maternity-javi0404-138c7b.jpg",
    "alt": "maternity photography by Javies Photography Studio",
    "caption": "Maternity",
    "category": "maternity",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "be1aa4856e8c",
    "src": "/images/gallery/maternity-javi0738-be1aa4.jpg",
    "alt": "maternity photography by Javies Photography Studio",
    "caption": "Maternity",
    "category": "maternity",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "6a07b177930a",
    "src": "/images/gallery/maternity-javi0779-6a07b1.jpg",
    "alt": "maternity photography by Javies Photography Studio",
    "caption": "Maternity",
    "category": "maternity",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "1d583425774e",
    "src": "/images/gallery/maternity-javi0841-1d5834.jpg",
    "alt": "maternity photography by Javies Photography Studio",
    "caption": "Maternity",
    "category": "maternity",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "847ed5425205",
    "src": "/images/gallery/maternity-javi1391-847ed5.jpg",
    "alt": "maternity photography by Javies Photography Studio",
    "caption": "Maternity",
    "category": "maternity",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "a3ef972e5e57",
    "src": "/images/gallery/maternity-javi1392hd-a3ef97.jpg",
    "alt": "maternity photography by Javies Photography Studio",
    "caption": "Maternity",
    "category": "maternity",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "3cdcd162802c",
    "src": "/images/gallery/maternity-javi1451-3cdcd1.jpg",
    "alt": "maternity photography by Javies Photography Studio",
    "caption": "Maternity",
    "category": "maternity",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "7b3ce7ee6853",
    "src": "/images/gallery/maternity-javi1511-7b3ce7.jpg",
    "alt": "maternity photography by Javies Photography Studio",
    "caption": "Maternity",
    "category": "maternity",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "d286c8661286",
    "src": "/images/gallery/maternity-javi3319-d286c8.jpg",
    "alt": "maternity photography by Javies Photography Studio",
    "caption": "Maternity",
    "category": "maternity",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "7f8989f8a32c",
    "src": "/images/gallery/maternity-javi3357-7f8989.jpg",
    "alt": "maternity photography by Javies Photography Studio",
    "caption": "Maternity",
    "category": "maternity",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "ed9f39e33393",
    "src": "/images/gallery/maternity-javi3416-ed9f39.jpg",
    "alt": "maternity photography by Javies Photography Studio",
    "caption": "Maternity",
    "category": "maternity",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "19f8f56bd768",
    "src": "/images/gallery/maternity-javi6252-19f8f5.jpg",
    "alt": "maternity photography by Javies Photography Studio",
    "caption": "Maternity",
    "category": "maternity",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "7790618c0ceb",
    "src": "/images/gallery/maternity-javi6287-779061.jpg",
    "alt": "maternity photography by Javies Photography Studio",
    "caption": "Maternity",
    "category": "maternity",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "eede1ceebf2c",
    "src": "/images/gallery/maternity-javi6481-eede1c.jpg",
    "alt": "maternity photography by Javies Photography Studio",
    "caption": "Maternity",
    "category": "maternity",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "90838a941746",
    "src": "/images/gallery/maternity-jennifer_maternity-(19)-90838a.jpg",
    "alt": "maternity photography by Javies Photography Studio",
    "caption": "Maternity",
    "category": "maternity",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "f2d00cc19936",
    "src": "/images/gallery/maternity-maternity-(17)-f2d00c.jpg",
    "alt": "maternity photography by Javies Photography Studio",
    "caption": "Maternity",
    "category": "maternity",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "d53e6d06f86f",
    "src": "/images/gallery/maternity-maternity-(19)-d53e6d.jpg",
    "alt": "maternity photography by Javies Photography Studio",
    "caption": "Maternity",
    "category": "maternity",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "e51bc13cdc4a",
    "src": "/images/gallery/maternity-maternity-(9)-e51bc1.jpg",
    "alt": "maternity photography by Javies Photography Studio",
    "caption": "Maternity",
    "category": "maternity",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "847346d91b53",
    "src": "/images/gallery/maternity-tily_maternitry-(4)-847346.jpg",
    "alt": "maternity photography by Javies Photography Studio",
    "caption": "Maternity",
    "category": "maternity",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "484a23c37311",
    "src": "/images/gallery/maternity-tily_maternitry-(7)-484a23.jpg",
    "alt": "maternity photography by Javies Photography Studio",
    "caption": "Maternity",
    "category": "maternity",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "d34a8b37d0d3",
    "src": "/images/gallery/milestone-20251127-casandra@7-(5)-d34a8b.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "3ede791445fb",
    "src": "/images/gallery/milestone-244a1102-3ede79.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "bf61bef69497",
    "src": "/images/gallery/milestone-244a2026-bf61be.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "d819d9706743",
    "src": "/images/gallery/milestone-244a2399-d819d9.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "d7bd09cdda3a",
    "src": "/images/gallery/milestone-244a5993-copy-d7bd09.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "b87101f1ef72",
    "src": "/images/gallery/milestone-244a8702-b87101.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 3866,
    "height": 4832,
    "ratio": 0.8001
  },
  {
    "id": "51d9a3f1acd3",
    "src": "/images/gallery/milestone-244a8768-51d9a3.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 1574,
    "ratio": 1.2706
  },
  {
    "id": "7847c37246c4",
    "src": "/images/gallery/milestone-244a9171-7847c3.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 1505,
    "ratio": 1.3289
  },
  {
    "id": "7c6a7ccd17ff",
    "src": "/images/gallery/milestone-244a9875-7c6a7c.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 2532,
    "ratio": 0.7899
  },
  {
    "id": "bfede4d418bc",
    "src": "/images/gallery/milestone-7-bfede4.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "b4f311b7fcf9",
    "src": "/images/gallery/milestone-abdul-samed@1-(16)-b4f311.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "3d50fea0f176",
    "src": "/images/gallery/milestone-adam@1-(12)-3d50fe.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "224c04d84255",
    "src": "/images/gallery/milestone-adam@1-(2)-copy-224c04.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "8d6124a2dd4e",
    "src": "/images/gallery/milestone-adele@1-(1)-8d6124.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 1505,
    "ratio": 1.3289
  },
  {
    "id": "812c718eb100",
    "src": "/images/gallery/milestone-adele@1-(7)-812c71.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "f0719c04027a",
    "src": "/images/gallery/milestone-amira@1-(10)-f0719c.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "6e0aa5d880d0",
    "src": "/images/gallery/milestone-amira@2-(4)-6e0aa5.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "88c90742af33",
    "src": "/images/gallery/milestone-amira@2-(7)-88c907.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "8b2b3e810e03",
    "src": "/images/gallery/milestone-animah@1-(15)-8b2b3e.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 1505,
    "ratio": 1.3289
  },
  {
    "id": "7bdcde7135e2",
    "src": "/images/gallery/milestone-ankomaa@1-(12)-7bdcde.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 1080,
    "height": 1350,
    "ratio": 0.8
  },
  {
    "id": "89d75d240535",
    "src": "/images/gallery/milestone-arielle-and-brielle@1-(1)-89d75d.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 1333,
    "ratio": 1.5004
  },
  {
    "id": "00456cbf4a65",
    "src": "/images/gallery/milestone-arielle@1-(13)-00456c.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "6228d94cfdea",
    "src": "/images/gallery/milestone-arielle@1-(7)-6228d9.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "b11649832e6a",
    "src": "/images/gallery/milestone-arnold@2-(20)-b11649.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "5d0582a1d14c",
    "src": "/images/gallery/milestone-arnold@2-(7)-5d0582.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "089e51fd8dee",
    "src": "/images/gallery/milestone-aseye@1-(11)-089e51.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "74514e8c666c",
    "src": "/images/gallery/milestone-audrey@1-(12)-74514e.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "df4cb428dd86",
    "src": "/images/gallery/milestone-audrey@1-(39)-df4cb4.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "e92479c24160",
    "src": "/images/gallery/milestone-audrey@2-(5)-e92479.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "86cb3c73049c",
    "src": "/images/gallery/milestone-audrey@5-(11)-86cb3c.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "c11a4e1d6c80",
    "src": "/images/gallery/milestone-audrey@5-(2)-c11a4e.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "425680a0cd9a",
    "src": "/images/gallery/milestone-audrey@5-(6)-425680.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "6161af0a0622",
    "src": "/images/gallery/milestone-austin@2-(12)-6161af.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "d92571c09d04",
    "src": "/images/gallery/milestone-austin@2-(18)-d92571.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "b3196ca25537",
    "src": "/images/gallery/milestone-austin@2-(6)-b3196c.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "d3e7653b9299",
    "src": "/images/gallery/milestone-awurayaa-(10)-d3e765.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 1505,
    "ratio": 1.3289
  },
  {
    "id": "396a71389027",
    "src": "/images/gallery/milestone-awurayaa-(11)-396a71.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 1505,
    "ratio": 1.3289
  },
  {
    "id": "afdb8841d6bd",
    "src": "/images/gallery/milestone-awurayaa-(18)-afdb88.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 1505,
    "ratio": 1.3289
  },
  {
    "id": "5ad9df531d82",
    "src": "/images/gallery/milestone-baake@1-(7)-5ad9df.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "3380977d9174",
    "src": "/images/gallery/milestone-baba@1-(10)-338097.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "cb452e7cbd44",
    "src": "/images/gallery/milestone-baba@1-(14)-cb452e.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "9f479808626b",
    "src": "/images/gallery/milestone-baffour@1-(18)-9f4798.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "10d44eeca6c5",
    "src": "/images/gallery/milestone-barimaba@1-(6)-10d44e.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "90eab75a5e7d",
    "src": "/images/gallery/milestone-bedrich@1-(16)-90eab7.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 1503,
    "ratio": 1.3307
  },
  {
    "id": "31ae4c57c8dd",
    "src": "/images/gallery/milestone-bedrich@1-(5)-31ae4c.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 2499,
    "ratio": 0.8003
  },
  {
    "id": "f32a5e4c85dc",
    "src": "/images/gallery/milestone-bernelle@1-(15)-f32a5e.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "a210599f65da",
    "src": "/images/gallery/milestone-bethany@1-(11)-copy-a21059.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "a3a0cc56c7f4",
    "src": "/images/gallery/milestone-brielle@1-(3)-a3a0cc.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "508ce8db583b",
    "src": "/images/gallery/milestone-bryan@1-(10)-508ce8.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "fd0fd0b066e3",
    "src": "/images/gallery/milestone-fiona-and-fallyn@5-(9)-fd0fd0.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "32d8443f6dea",
    "src": "/images/gallery/milestone-jaylen@1-(18)-32d844.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "f43148c41a77",
    "src": "/images/gallery/milestone-jaynaya@1-(13)-f43148.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "a331d48949bd",
    "src": "/images/gallery/milestone-jaynaya@1-(19)-a331d4.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "31661b6caed9",
    "src": "/images/gallery/milestone-jeanelle@1-(12)-31661b.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "3805e318f788",
    "src": "/images/gallery/milestone-jpsi9001-3805e3.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "671d2d0652c5",
    "src": "/images/gallery/milestone-jpsi9953-671d2d.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "4b94e77f2190",
    "src": "/images/gallery/milestone-osahene-@2-(5)-4b94e7.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "f51e3a92fd41",
    "src": "/images/gallery/milestone-zaine@1-(11)-f51e3a.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "3b24f793748c",
    "src": "/images/gallery/milestone-zaine@1-(5)-3b24f7.jpg",
    "alt": "milestone photography by Javies Photography Studio",
    "caption": "Milestone",
    "category": "milestone",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "d2a26d0c7d14",
    "src": "/images/gallery/newborn-244a0656-d2a26d.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "3d38dfd1f76a",
    "src": "/images/gallery/newborn-244a0675-3d38df.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "b49ef3c04316",
    "src": "/images/gallery/newborn-244a0709-b49ef3.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "f920d672eb3e",
    "src": "/images/gallery/newborn-244a6407-f920d6.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "79681939988e",
    "src": "/images/gallery/newborn-244a6498-796819.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 1125,
    "ratio": 1.7778
  },
  {
    "id": "6c22f8c14f55",
    "src": "/images/gallery/newborn-244a6585-6c22f8.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "572237a77a8c",
    "src": "/images/gallery/newborn-244a8723-572237.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 5952,
    "height": 4480,
    "ratio": 1.3286
  },
  {
    "id": "5bd3c30e088a",
    "src": "/images/gallery/newborn-244a8783-5bd3c3.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 5600,
    "height": 4480,
    "ratio": 1.25
  },
  {
    "id": "d9e47d417c75",
    "src": "/images/gallery/newborn-baby-deron@7ms-(10)-d9e47d.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "24267bc72b8e",
    "src": "/images/gallery/newborn-baby-deron@7ms-(6)-24267b.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "a682e2802bbe",
    "src": "/images/gallery/newborn-baby-ethan@6ms-(1)-a682e2.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "c249aa0ef561",
    "src": "/images/gallery/newborn-baby-ethan@6ms-(15)-c249aa.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 1505,
    "ratio": 1.3289
  },
  {
    "id": "1c8c3b6cc5ad",
    "src": "/images/gallery/newborn-baby-ethan@6ms-(19)-1c8c3b.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 1505,
    "ratio": 1.3289
  },
  {
    "id": "9b41e6e8d0b1",
    "src": "/images/gallery/newborn-baby-ethan@6ms-(4)-9b41e6.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "3e244d0f3364",
    "src": "/images/gallery/newborn-baby-fiifi@6ms-(10)-3e244d.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 2657,
    "ratio": 0.7527
  },
  {
    "id": "7bbc3fa3e16c",
    "src": "/images/gallery/newborn-baby-fiifi@6ms-(11)-7bbc3f.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 1505,
    "ratio": 1.3289
  },
  {
    "id": "06c04e718907",
    "src": "/images/gallery/newborn-baby-fiifi@6ms-(12)-06c04e.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 1506,
    "ratio": 1.328
  },
  {
    "id": "8555fa1046b2",
    "src": "/images/gallery/newborn-baby-fiifi@6ms-(13)-8555fa.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "58122a869667",
    "src": "/images/gallery/newborn-baby-fiifi@6ms-(2)-58122a.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "061e6abbcd74",
    "src": "/images/gallery/newborn-baby-fiifi@6ms-(3)-061e6a.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "51cc8bb9d63a",
    "src": "/images/gallery/newborn-baby-fiifi@6ms-(4)-51cc8b.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "d4a51c552559",
    "src": "/images/gallery/newborn-baby-fiifi@6ms-(5)-d4a51c.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 1505,
    "ratio": 1.3289
  },
  {
    "id": "b96775302ce0",
    "src": "/images/gallery/newborn-baby-fiifi@6ms-(6)-b96775.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 1505,
    "ratio": 1.3289
  },
  {
    "id": "31afe0c31893",
    "src": "/images/gallery/newborn-baby-fiifi@6ms-(7)-31afe0.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "9cf56fe41b0c",
    "src": "/images/gallery/newborn-baby-fiifi@6ms-(8)-9cf56f.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 1505,
    "ratio": 1.3289
  },
  {
    "id": "e8eae51e25d1",
    "src": "/images/gallery/newborn-baby-keliven-(11)-e8eae5.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "6231da4f22fc",
    "src": "/images/gallery/newborn-baby-keliven-(17)-6231da.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "21e718dfc005",
    "src": "/images/gallery/newborn-baby-keliven-(22)-21e718.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "4279b214a62b",
    "src": "/images/gallery/newborn-baby-nana-kwame-(1)-4279b2.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "fe1035c7cd95",
    "src": "/images/gallery/newborn-baby-nana-kwame-(12)-fe1035.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "a477474f5f61",
    "src": "/images/gallery/newborn-baby-nana-kwame-(21)-a47747.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "1168a66016e3",
    "src": "/images/gallery/newborn-baby-nana-kwame-(8)-1168a6.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "29715da88b4f",
    "src": "/images/gallery/newborn-baby-naseda-(1)-29715d.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "0e6b2671dd5d",
    "src": "/images/gallery/newborn-baby-naseda-(12)-0e6b26.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "9b9b216740ea",
    "src": "/images/gallery/newborn-baby-rafui@6ms-(2)-9b9b21.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "93ad297c85ac",
    "src": "/images/gallery/newborn-baby-rafui@6ms-(5)-93ad29.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "22cc097a1131",
    "src": "/images/gallery/newborn-baby-rafui@6ms-(6)-22cc09.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "2c51aae82abc",
    "src": "/images/gallery/newborn-baby-yaa-(11)-2c51aa.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "423c7955840c",
    "src": "/images/gallery/newborn-baby-yaa-(4)-423c79.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "e993eb9413b0",
    "src": "/images/gallery/newborn-jayden-&-kayden-(2)-e993eb.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 1505,
    "ratio": 1.3289
  },
  {
    "id": "61d9eb2de957",
    "src": "/images/gallery/newborn-jayden-&-kayden-(20)-61d9eb.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 1505,
    "ratio": 1.3289
  },
  {
    "id": "4d447dcef8b3",
    "src": "/images/gallery/newborn-jayden-&-kayden-(3)-4d447d.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 1506,
    "ratio": 1.328
  },
  {
    "id": "514a572cc60f",
    "src": "/images/gallery/newborn-jayden-&-kayden-(4)-514a57.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "1818fd03426d",
    "src": "/images/gallery/newborn-jayden-&-kayden-(5)-1818fd.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "e1b8260985d7",
    "src": "/images/gallery/newborn-jayden-&-kayden-(6)-e1b826.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 2501,
    "ratio": 0.7997
  },
  {
    "id": "8a64be6e3f2e",
    "src": "/images/gallery/newborn-jayden-&-kayden-(7)-8a64be.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "80a9d3479a42",
    "src": "/images/gallery/newborn-jayden-&-kayden-(8)-80a9d3.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "17ae07536a79",
    "src": "/images/gallery/newborn-jpsi1281-17ae07.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 1505,
    "ratio": 1.3289
  },
  {
    "id": "fb052d031f37",
    "src": "/images/gallery/newborn-jpsi1299-fb052d.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 1505,
    "ratio": 1.3289
  },
  {
    "id": "e4bd6717fca2",
    "src": "/images/gallery/newborn-jpsi1329-e4bd67.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "f3a515c6e414",
    "src": "/images/gallery/newborn-jpsi1330-f3a515.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 1333,
    "ratio": 1.5004
  },
  {
    "id": "221377122e12",
    "src": "/images/gallery/newborn-jpsi1331-221377.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 1333,
    "ratio": 1.5004
  },
  {
    "id": "55f152619785",
    "src": "/images/gallery/newborn-jpsi1354-55f152.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 1505,
    "ratio": 1.3289
  },
  {
    "id": "e48c57ebe188",
    "src": "/images/gallery/newborn-jpsi1358-e48c57.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 2657,
    "ratio": 0.7527
  },
  {
    "id": "5c30f56e13c2",
    "src": "/images/gallery/newborn-jpsi1369-5c30f5.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 1505,
    "ratio": 1.3289
  },
  {
    "id": "d60652514fcb",
    "src": "/images/gallery/newborn-jpsi1400-d60652.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 1505,
    "ratio": 1.3289
  },
  {
    "id": "87e3847943d3",
    "src": "/images/gallery/newborn-jpsi1416-87e384.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 2499,
    "ratio": 0.8003
  },
  {
    "id": "3846f16e5979",
    "src": "/images/gallery/newborn-milan@3ms-(12)-3846f1.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 2501,
    "ratio": 0.7997
  },
  {
    "id": "ece349e7327d",
    "src": "/images/gallery/newborn-milan@3ms-(14)-ece349.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "b0882accc622",
    "src": "/images/gallery/newborn-skylar@1-(13)-b0882a.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "d59e4e78ba2f",
    "src": "/images/gallery/newborn-skylar@1-(16)-d59e4e.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "0681194f419e",
    "src": "/images/gallery/newborn-sreyhan@3ms-(22)-068119.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 1503,
    "ratio": 1.3307
  },
  {
    "id": "34b3cde0462d",
    "src": "/images/gallery/newborn-sreyhan@3ms-(4)-34b3cd.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "3ffc631239e1",
    "src": "/images/gallery/newborn-zaine@1-(10)-3ffc63.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "142e95eca9fe",
    "src": "/images/gallery/newborn-zaine@1-(7)-142e95.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "7bc26c7bffb2",
    "src": "/images/gallery/newborn-zoey@2-(19)-7bc26c.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "02408356a4bf",
    "src": "/images/gallery/newborn-zoey@2-(23)-024083.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "ef5548d8353d",
    "src": "/images/gallery/newborn-zoie@1-(15)-ef5548.jpg",
    "alt": "newborn photography by Javies Photography Studio",
    "caption": "Newborn",
    "category": "newborn",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "ef49ca0c8ffb",
    "src": "/images/gallery/portrait-_mg_1790-ef49ca.jpg",
    "alt": "portrait photography by Javies Photography Studio",
    "caption": "Portrait",
    "category": "portrait",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "25380745f724",
    "src": "/images/gallery/portrait-jpsi0430-253807.jpg",
    "alt": "portrait photography by Javies Photography Studio",
    "caption": "Portrait",
    "category": "portrait",
    "width": 632,
    "height": 473,
    "ratio": 1.3362
  },
  {
    "id": "99321fcbffd4",
    "src": "/images/gallery/traditional-abdul-samed@1-(4)-99321f.jpg",
    "alt": "traditional photography by Javies Photography Studio",
    "caption": "Traditional",
    "category": "traditional",
    "width": 2000,
    "height": 2501,
    "ratio": 0.7997
  },
  {
    "id": "fd72442f3918",
    "src": "/images/gallery/traditional-abdul-samed@1-(6)-fd7244.jpg",
    "alt": "traditional photography by Javies Photography Studio",
    "caption": "Traditional",
    "category": "traditional",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "e2d740cc18d6",
    "src": "/images/gallery/traditional-adam@1-(27)-e2d740.jpg",
    "alt": "traditional photography by Javies Photography Studio",
    "caption": "Traditional",
    "category": "traditional",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "20d1fa4e2bba",
    "src": "/images/gallery/traditional-adi@3-(5)-20d1fa.jpg",
    "alt": "traditional photography by Javies Photography Studio",
    "caption": "Traditional",
    "category": "traditional",
    "width": 2000,
    "height": 2658,
    "ratio": 0.7524
  },
  {
    "id": "6113ce2013bf",
    "src": "/images/gallery/traditional-aileen@1-(30)-6113ce.jpg",
    "alt": "traditional photography by Javies Photography Studio",
    "caption": "Traditional",
    "category": "traditional",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "6d206bc1f1cf",
    "src": "/images/gallery/traditional-awurayaa-(3)-6d206b.jpg",
    "alt": "traditional photography by Javies Photography Studio",
    "caption": "Traditional",
    "category": "traditional",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "afeb58a0d78a",
    "src": "/images/gallery/traditional-barimaba@1-(18)-afeb58.jpg",
    "alt": "traditional photography by Javies Photography Studio",
    "caption": "Traditional",
    "category": "traditional",
    "width": 2000,
    "height": 2501,
    "ratio": 0.7997
  },
  {
    "id": "9393fff828ca",
    "src": "/images/gallery/traditional-bohyeba@1-(10)-9393ff.jpg",
    "alt": "traditional photography by Javies Photography Studio",
    "caption": "Traditional",
    "category": "traditional",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "50c5e0ecfd72",
    "src": "/images/gallery/traditional-bohyeba@1-(12)-50c5e0.jpg",
    "alt": "traditional photography by Javies Photography Studio",
    "caption": "Traditional",
    "category": "traditional",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "31c7a02c22ce",
    "src": "/images/gallery/traditional-dilys@5-(5)-31c7a0.jpg",
    "alt": "traditional photography by Javies Photography Studio",
    "caption": "Traditional",
    "category": "traditional",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "ce2c20a2d2cd",
    "src": "/images/gallery/traditional-dilys@5-(6)-ce2c20.jpg",
    "alt": "traditional photography by Javies Photography Studio",
    "caption": "Traditional",
    "category": "traditional",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "61d1a40bd788",
    "src": "/images/gallery/traditional-javi7118-61d1a4.jpg",
    "alt": "traditional photography by Javies Photography Studio",
    "caption": "Traditional",
    "category": "traditional",
    "width": 1080,
    "height": 1350,
    "ratio": 0.8
  },
  {
    "id": "9a4854214a83",
    "src": "/images/gallery/traditional-jeslyn@1-(8)-9a4854.jpg",
    "alt": "traditional photography by Javies Photography Studio",
    "caption": "Traditional",
    "category": "traditional",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "d93c2dd8ab4f",
    "src": "/images/gallery/traditional-jpsi9934-(2)-d93c2d.jpg",
    "alt": "traditional photography by Javies Photography Studio",
    "caption": "Traditional",
    "category": "traditional",
    "width": 2000,
    "height": 2658,
    "ratio": 0.7524
  },
  {
    "id": "70fafd5a319d",
    "src": "/images/gallery/traditional-milan@1-(3)-70fafd.jpg",
    "alt": "traditional photography by Javies Photography Studio",
    "caption": "Traditional",
    "category": "traditional",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "80b9df4a0254",
    "src": "/images/gallery/traditional-nana-kwame-and-ama-(11)-80b9df.jpg",
    "alt": "traditional photography by Javies Photography Studio",
    "caption": "Traditional",
    "category": "traditional",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "694f5653eae6",
    "src": "/images/gallery/traditional-nana-kwame-and-ama-(13)-694f56.jpg",
    "alt": "traditional photography by Javies Photography Studio",
    "caption": "Traditional",
    "category": "traditional",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "edf11927015f",
    "src": "/images/gallery/traditional-ngwu@1-(15)-edf119.jpg",
    "alt": "traditional photography by Javies Photography Studio",
    "caption": "Traditional",
    "category": "traditional",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "a0b100a44b20",
    "src": "/images/gallery/traditional-ngwu@1-(18)-a0b100.jpg",
    "alt": "traditional photography by Javies Photography Studio",
    "caption": "Traditional",
    "category": "traditional",
    "width": 2000,
    "height": 1600,
    "ratio": 1.25
  },
  {
    "id": "8d4acd9dc9fd",
    "src": "/images/gallery/traditional-ortopah@1-(6)-8d4acd.jpg",
    "alt": "traditional photography by Javies Photography Studio",
    "caption": "Traditional",
    "category": "traditional",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "f77274b1d87a",
    "src": "/images/gallery/traditional-princess@5-(7)-f77274.jpg",
    "alt": "traditional photography by Javies Photography Studio",
    "caption": "Traditional",
    "category": "traditional",
    "width": 2000,
    "height": 2657,
    "ratio": 0.7527
  },
  {
    "id": "56d49ab5cbcd",
    "src": "/images/gallery/traditional-princess@5-(8)-56d49a.jpg",
    "alt": "traditional photography by Javies Photography Studio",
    "caption": "Traditional",
    "category": "traditional",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  },
  {
    "id": "1eb1e6b36874",
    "src": "/images/gallery/traditional-sewaa@10-(11)-1eb1e6.jpg",
    "alt": "traditional photography by Javies Photography Studio",
    "caption": "Traditional",
    "category": "traditional",
    "width": 2000,
    "height": 2500,
    "ratio": 0.8
  }
];
